### ISSUE TITLE
Жесткая зависимость от версий

### ISSUE THREAD

**Issue by glader** [whisklabs/airflow-clickhouse-plugin#13]
Я хотел воспользоваться плагином, но у нас в системе clickhouse-driver==0.1.3 и apache-airflow==1.10.8, а в requirements написано
`clickhouse-driver==0.1.2
apache-airflow==1.10.6`
Поэтому установка через pip невозможна.
Я очень сомневаюсь, что различия в minor делают пакеты несовместимыми. Предлагаю писать
`clickhouse-driver<0.2.0
apache-airflow<1.11.0`

**Comment by viktortnk** [comment]
I agree, it doesn't make sense to lock on specific versions on libs

I checked couple of approaches people use:

1. they don't specify requirements in setup.py at all. in that case it would be required to set up clickhouse-driver manually, which I think is acceptable
2. in one place I saw version specified as `library>=0.X.X`.

In any case I don't think it makes sense to specify Airflow as dependency at all. Plugin only does't make sense within Airflow env

@bryzgaloff

**Comment by bryzgaloff** [comment]
The plugin was first used at Whisk in Google Cloud Composer environment. And the version of Airflow there [is exactly 1.10.6](https://cloud.google.com/composer/docs/concepts/versioning/composer-versions) (composer-1.10.3-airflow-1.10.6). I did not have enough time to investigate the differences between minor versions.

Specifying none of the requirements seems to be a bad practice to me. Using an external dependency personally I would like to know its dependencies. We have at least to specify `install_requires` in `setup.py`. By fixing only the lower version of the dependency we put further deprecated features usage at risk.

Both [Airflow](https://airflow.apache.org/docs/stable/changelog.html) and [clickhouse-driver](https://github.com/mymarilyn/clickhouse-driver/blob/master/CHANGELOG.md) changelogs seem backwards compatible to me in terms of minor versions. So I would rather partially accept proposal with `clickhouse-driver<0.2.0 apache-airflow<1.11.0`.

@glader could you please create a PR and check if that works for your environment? We need to specify lower versions as well, so it should be smth like `clickhouse-driver>=0.1.2,<0.2.0` and `apache-airflow>=1.10.6,<1.11.0`. If I am not mistaken, this is a supported `pip` versions syntax.

**Comment by ne1r0n** [comment]
I can add that with airflow version 1.10.10 and clickhouse-driver 0.1.3 it work fine.

**Comment by glader** [comment]
https://github.com/whisklabs/airflow-clickhouse-plugin/pull/14

**Comment by bryzgaloff** [comment]
Merged into master, thank you for your participation
