### ISSUE TITLE
Support for clickhouse driver 0.2.0

### ISSUE THREAD

**Issue by anwinged** [whisklabs/airflow-clickhouse-plugin#24]
Please add support for clickhouse driver [0.2.0 version](https://pypi.org/project/clickhouse-driver/0.2.0/)

**Comment by bryzgaloff** [comment]
@anwinged thank you for a notice. Do you have any issues with 0.2.0 using Airflow ClickHouse plugin?

Plugin tests pass with `clickhouse-driver==0.2.0` is installed. So I am going to simply add `clickhouse-driver~=0.2.0` as a dependency to `setup.py` and this should work, I believe. In case you have any issues, please share details.

Before the 0.2.0 dependency update is published, you may simply install `clickhouse-driver==0.2.0`. Feel free to share any feedback.

**Comment by bryzgaloff** [comment]
@anwinged could you please test `clickhouse-driver==0.2.0` on your use case by installing it explicitly via `pip install clickhouse-driver==0.2.0`? This can help a lot to verify whether simple upgrade works. Thank you in advance.

If anything breaks, you may revert back easily by running `pip install clickhouse-driver~=0.1.3`.

**Comment by ne1r0n** [comment]
Hello guys, any progress here? I want to use this plugin with airflow 2.1.0. Just tested it with airflow 2.1.0 and clickhouse-driver 0.2.0. Didn't notice any issue except for some negligible deprecation warning:
```
/airflow-clickhouse-plugin/airflow_clickhouse_plugin/operators/clickhouse_operator.py:9 DeprecationWarning: This decorator is deprecated.

In previous versions, all subclasses of BaseOperator must use apply_default decorator for the`default_args` feature to work properly.

In current version, it is optional. The decorator is applied automatically using the metaclass.
```
@bryzgaloff, could you please change the requirements.txt file for both dependencies together?

**Comment by bryzgaloff** [comment]
@ne1r0n could you please make a PR for that? Including the following changes:
* Update requirements.
* Update README (it states that we support 2.0.1 now).
* Drop this line: https://github.com/whisklabs/airflow-clickhouse-plugin/blob/master/airflow_clickhouse_plugin/operators/clickhouse_operator.py#L13

Also:
* Make sure warning is gone. BTW which version have you started seen this warning? 2.1.0 only? Or any Airflow 2+?
* Make sure tests pass. I have recently configured CI pipeline for the repo so this should be run automatically on push/PR to the repo. But better run it first locally, at least unit tests.

Highly appreciated:
* Make sure you have actually tested your setup with airflow==2.1.0 and clickhouse-driver==0.2.0 and faced no issues.

Thank you in advance!

**Comment by ne1r0n** [comment]
I started seen warnings only on 2.1.0

**Comment by bryzgaloff** [comment]
See release v0.7.0: https://github.com/whisklabs/airflow-clickhouse-plugin/releases/tag/v0.7.0
