### ISSUE TITLE
doesn't see the library

### ISSUE THREAD

**Issue by UrcaDeLima** [whisklabs/airflow-clickhouse-plugin#25]
Unable to import 'airflow.operators.clickhouse_operator'
I did everything according to the instructions, tell me what to do

**Comment by UrcaDeLima** [comment]
![kceFtEH4e4g](https://user-images.githubusercontent.com/48882691/109510878-90159400-7ab3-11eb-9d40-35b79b07b173.jpg)
![iA4KBZ1RIhc](https://user-images.githubusercontent.com/48882691/109511259-ea165980-7ab3-11eb-9cdd-87e473729913.jpg)

**Comment by bryzgaloff** [comment]
How have you installed Airflow v2.0.1? It is currently not supported. The plugin itself [installs Airflow~=1.10.6](https://github.com/whisklabs/airflow-clickhouse-plugin/blob/e79c79834d96dd9d2756a1619bf9c52ace3670a5/setup.py#L30). Use Airflow of an appropriate version. To do this, either run `pip install apache-airflow==1.10.6` or recreate the environment with fresh installation of the plugin.

You may share your issues with Airflow v2 on #23.

**Comment by UrcaDeLima** [comment]
when trying to install pip install apache-air flow==1.10.6, the following compatibility errors occur
![image](https://user-images.githubusercontent.com/48882691/109640880-125c9180-7b62-11eb-994c-b9de647e8545.png)

**Comment by UrcaDeLima** [comment]
are there any other ways to connect to the clickhouse with airflow? I need to write logs from a file there, but I only found methods for postgresql, mysql, and sqlite, are other databases supported out of the box, or do I need to write separate processing methods like you did?

**Comment by bryzgaloff** [comment]
> when trying to install pip install apache-air flow==1.10.6, the following compatibility errors occur

Your сап file from Airflow v2.0 was preserved and cannot be parsed by Airflow v1.

Do the following: `pip uninstall apache-airflow && rm -rf ~/airflow && pip install airflow-clickhouse-plugin`

Now this should work. **Warning**: this will remove airflow database either (when removing `~/airflow` dir).

> are there any other ways to connect to the clickhouse with airflow?

You may use [ClickHouse HTTP API](https://clickhouse.tech/docs/en/interfaces/http/).

> I only found methods for postgresql, mysql, and sqlite, are other databases supported out of the box

[Plenty of them](https://airflow.apache.org/docs/apache-airflow/1.10.14/_api/airflow/contrib/operators/index.html). But ClickHouse requires `airflow-clickhouse-plugin` plugin to be installed if you want to do some complex `clickhouse-driver`-based operations. For simple interaction with ClickHouse HTTP API may be enough.
