### ISSUE TITLE
Bridge version for airflow 1.10.15

### ISSUE THREAD

**Issue by gkarg** [whisklabs/airflow-clickhouse-plugin#30]
While versions of airflow-clickhouse-plugin that support airflow 2 and airflow 1.10.6 both exist, there ain't a version that could help with airflow migration, via the 1.10.15 path.

It would've been very useful to have a version (say, 0.5.8?), which would still work on airflow 1.10.15, yet would get rid of this warning:
```
.../site-packages/airflow_clickhouse_plugin/__init__.py:7: FutureWarning: Registering operators or sensors in plugins is deprecated -- these should be treated like 'plain' python modules, and imported normally in DAGs.
```

Thanks in advance.

**Comment by bryzgaloff** [comment]
Warnings don't block you from using plugin. Do you encounter any blocking issues like exceptions?

**Comment by gkarg** [comment]
> Warnings don't block you from using plugin. Do you encounter any blocking issues like exceptions?

Nope, everything works fine.

Warning don't block the usage indeed, but are still a bit annoying, especially if you have some CI/CD which checks for those (like we do).

Anyways, it's a minor thing, so if you don't think it's worth it, I understand completely.

**Comment by bryzgaloff** [comment]
Yes, I think it is not worth adding to a public repository.

As a workaround you may create you own fork and patch the desired branch (to get rid of warnings) so you may temporarily use an older version of a plugin. Once you are able to migrate to any version supported by our repository, you may switch back to it.
