### ISSUE TITLE
Error with JDBC connection

### ISSUE THREAD

**Issue by silverbullet1** [whisklabs/airflow-clickhouse-plugin#31]
Hi,

I'm using Airflow v2.1.3
I am trying to use this plugin to connect to my clickhouse(hosted on a docker) via a JDBC connection. i am using [clickhouse4j](https://github.com/blynkkk/clickhouse4j) for that. I have defined a JDBC connection in Airflow UI but when I try to run my DAG, it gives this error:

> 
> [2021-09-23 16:02:33,871] {taskinstance.py:1462} ERROR - Task failed with exception
> Traceback (most recent call last):
>   File "/opt/anaconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1164, in _run_raw_task
>     self._prepare_and_execute_task_with_callbacks(context, task)
>   File "/opt/anaconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1282, in _prepare_and_execute_task_with_callbacks
>     result = self._execute_task(context, task_copy)
>   File "/opt/anaconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1312, in _execute_task
>     result = task_copy.execute(context=context)
>   File "/opt/anaconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow_clickhouse_plugin/operators/clickhouse_operator.py", line 33, in execute
>     return hook.run(self._sql, self._parameters)
>   File "/opt/anaconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow_clickhouse_plugin/hooks/clickhouse_hook.py", line 62, in run
>     with disconnecting(self.get_conn()) as conn:
>   File "/opt/anaconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow_clickhouse_plugin/hooks/clickhouse_hook.py", line 33, in get_conn
>     return Client(conn.host or 'localhost', **connection_kwargs)
>   File "/opt/anaconda3/envs/airflow-tutorial/lib/python3.7/site-packages/clickhouse_driver/client.py", line 87, in __init__
>     self.connection = Connection(*args, **kwargs)
> TypeError: __init__() got an unexpected keyword argument 'extra__jdbc__drv_clsname'

Here is my task code in DAG :

> to_clickhouse_task = ClickHouseOperator(
>     task_id='to_clickhouse_task',
>     database='default',
>     sql=(
>         '''
>         ... some sql command ...
>         '''
>     ),
>     clickhouse_conn_id='clickhouse-jdbc',
>     dag=dag
> )

Also, I am able to connect to the clickhouse docker image on my host machine using CURL.

**Comment by bryzgaloff** [comment]
Hi @silverbullet1, the plugin does not support JDBC connections. It uses native ClickHouse protocol implemented using https://github.com/mymarilyn/clickhouse-driver. See credentials schema on README: https://github.com/whisklabs/airflow-clickhouse-plugin#clickhouse-connection-schema. No other arguments, including `extra__jdbc__drv_clsname` are not supported.

**Comment by silverbullet1** [comment]
Oops, my bad. Thanks for the quick response.
I have another question, what type of connection do i make in Airflow for the one which is referred in clickhouse_conn_id.

**Comment by bryzgaloff** [comment]
Generic connection is suitable. Leave Conn Type field empty and set the following attributes: https://github.com/whisklabs/airflow-clickhouse-plugin/blob/master/airflow_clickhouse_plugin/hooks/clickhouse_hook.py#L20-L33

You may see clickhouse-driver's `Client` schema here: https://clickhouse-driver.readthedocs.io/en/latest/api.html?highlight=client#clickhouse_driver.connection.Connection (`Client` propagates all the arguments to `Connection`).

Provide extra (non-common Airflow connection) parameters through Extra field if needed using JSON format.

**Comment by silverbullet1** [comment]
Thank you so much! :) It works now.
