### ISSUE TITLE
There is no connection ty

### ISSUE THREAD

**Issue by TranscendenceCat** [whisklabs/airflow-clickhouse-plugin#34]

**Comment by bryzgaloff** [comment]
Any help required here?

**Comment by mcrot** [comment]
Probably similar for me .. I don't fully understand how to setup the connection in airflow using the plugin.
First I expected a connection type "Clickhouse", but according to #36 one has to choose "HTTP" or "SQlite", not sure.
Both does not work for me yet, still trying to figure it out.

It would be good to mention in the "Usage" section, which connection type is expected to work,
so users can narrow down problems when connecting.

**Comment by bryzgaloff** [comment]
Hi @mcrot, thank you for sharing. I have updated README, see my comment in the original issue: https://github.com/whisklabs/airflow-clickhouse-plugin/issues/36#issuecomment-1207668885
